pipeline {
    agent none
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'python:3.10-alpine'
                }
            }
            steps {
                sh 'python -m py_compile Backend/app.py'
            }
        }
        stage('Test') {
            agent {
                docker {
                    image 'python:3.10-alpine'
                }
            }
            steps {
                // Install pytest within the container
                sh 'pip install pytest'
                
                // Run both integration and validation tests
                sh 'pytest --verbose --junit-xml test-reports/results.xml Backend/integration_test.py Backend/validation_test.py'
            }
            post {
                always {
                    junit 'test-reports/results.xml'
                }
            }
        }
    }
}
