pipeline {
    agent {
        docker {
            image 'flask-api'
            args '-p 5000:5000'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'docker build -t flask-api .'
            }
        }
        stage('Test') {
            steps {
                sh 'docker run --rm flask-api pytest'
            }
        }
        stage('Deploy') {
            steps {
                sh 'docker run -d -p 5000:5000 flask-api'
            }
        }
    }
}